$(function(){ 
   $(".like_button").each(function(){
        $(this).hover(function(){
            $(this).addClass("like_hover");
        },function(){
            $(this).removeClass("like_hover");
        });
    });
});